service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [ SQSQueue, Arn ]
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties: 
        Endpoint: shvets.ivan@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    

custom:
  webpack:
    includeModules: false

package:
  individually: true

plugins:
  - serverless-webpack

functions:
  getProducts:
    handler: handler.getProductsList
    environment:
      TABLE_NAME: products
    events:
      - httpApi:
          path: /products
          method: get
  getProduct:
    handler: handler.getProductById
    environment:
      TABLE_NAME: products
    events:
      - httpApi:
          path: /products/{id}
          method: get
  getStock:
    handler: handler.getStock
    environment:
      TABLE_NAME: stocks
    events:
      - httpApi:
          path: /stock
          method: get
  postProduct:
    handler: handler.putProduct
    environment:
      PRODUCTS_TABLE: products
      STOCK_TABLE: stocks
    events:
      - httpApi:
          path: /products
          method: post
  getStockProducts:
    handler: handler.getStockProducts
    environment:
      TABLE_NAME: products
      STOCK_TABLE: stocks
    events:
      - httpApi:
          path: /stock-products
          method: get
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs: 
          batchSize: 5
          arn: 
            Fn::GetAtt: 
              - SQSQueue
              - Arn