service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

custom:
  webpack:
    includeModules: false

package:
  individually: true

plugins:
  - serverless-webpack

functions:
  getProducts:
    handler: handler.getProductsList
    environment:
      TABLE_NAME: products
    events:
      - http:
          path: /products
          method: get
          cors: true
  getProduct:
    handler: handler.getProductById
    environment:
      TABLE_NAME: stocks
    events:
      - http:
          path: /products/{id}
          method: get
          cors: true
