const products = [
  {
    img: "keychron-k4",
    description: "Normal profile wireless mechanical keyboard",
    price: 127,
    title: "Keychron K4",
    count: 10,
    id: 1,
  },
  {
    img: "nuphy-air75",
    description: "Low profile wireless mechanical keyboard",
    price: 99,
    title: "NuPhy Air 75",
    count: 12,
    id: 2,
  },
  {
    img: "air75-case",
    description: "Case and mobile devices carrier",
    price: 20,
    title: "Case for NuPhy Air 75",
    count: 23,
    id: 3,
  },
  {
    img: "case-keychronk4",
    description: "Case for safe transportation",
    price: 30,
    title: "Case for Keychron K4",
    count: 12,
    id: 4,
  },
  {
    img: "full-profile-red",
    description:
      "Premium smooth and tactile typing experience for Keychrone K4. Normal profile",
    price: 19,
    title: "Gateron Phantom Switch",
    count: 1,
    id: 5,
  },
  {
    img: "full-profile-light-blue",
    description: "Linear and smooth switch for Keychrone K4. Normal profile",
    price: 69,
    title: "Gateron CJ Switch",
    id: 6,
  },
  {
    img: "full-profile-yellow",
    description:
      "Switches with a shorter travel distance of 3.5mm for Keychrone K4. Normal profile",
    price: 75,
    title: "Gateron Yellow Ink V2",
    count: 23,
    id: 7,
  },
  {
    img: "Keychron-K4-rest-resin",
    description: "Perfect for Keychrone K4",
    price: 30,
    title: "Resin palm rest",
    count: 3,
    id: 8,
  },
  {
    img: "palm-rests/KeychronK4-rest-wood",
    description: "Perfect for Keychrone K4",
    price: 40,
    title: "Wood palm rest",
    count: 5,
    id: 9,
  },
  {
    img: "nuphy-air75-rest",
    description: "Ideal for NuPhy Air 75",
    price: 20,
    title: "Resin palm rest",
    count: 9,
    id: 10,
  },
  {
    img: "keychron-black",
    description: "For Keychrone K4",
    price: 45,
    title: "Black PBT Keycaps",
    count: 9,
    id: 11,
  },
  {
    img: "keychron-green-keycaps",
    description: "For Keychrone K4",
    price: 50,
    title: "Green PBT Keycaps",
    count: 9,
    id: 12,
  },
  {
    img: "keychron-lambda",
    description: "For Keychrone K4",
    price: 55,
    title: "Lambda PBT Keycaps",
    count: 9,
    id: 13,
  },
  {
    img: "keychron-mint",
    description: "For Keychrone K4",
    price: 45,
    title: "Mint PBT Keycaps",
    count: 9,
    id: 14,
  },
  {
    img: "keychron-warm-gradient-2",
    description: "For Keychrone K4",
    price: 35,
    title: "Gradient PBT Keycaps",
    count: 9,
    id: 15,
  },
  {
    img: "keychron-warm-gradient",
    description: "For Keychrone K4",
    price: 50,
    title: "Purple PBT Keycaps",
    count: 9,
    id: 16,
  },
];

export default products;
